definitions:
  dispute.CloseDisputeRequest:
    properties:
      dispute_id:
        type: integer
    required:
    - dispute_id
    type: object
  dispute.CreateDisputeRequest:
    properties:
      order_id:
        type: integer
      reason:
        maxLength: 100
        type: string
    required:
    - order_id
    - reason
    type: object
  dispute.ListDisputesRequest:
    properties:
      dispute_id:
        type: integer
      page:
        minimum: 1
        type: integer
      page_size:
        maximum: 100
        minimum: 1
        type: integer
      status:
        enum:
        - disputing
        - refund
        - closed
        type: string
    type: object
  dispute.RefundReviewRequest:
    properties:
      dispute_id:
        type: integer
      reason:
        maxLength: 100
        type: string
      status:
        enum:
        - refund
        - closed
        type: string
    required:
    - dispute_id
    - status
    type: object
  merchant.CreateAPIKeyRequest:
    properties:
      app_description:
        maxLength: 100
        type: string
      app_homepage_url:
        maxLength: 100
        type: string
      app_name:
        maxLength: 20
        type: string
      notify_url:
        maxLength: 100
        type: string
      redirect_uri:
        maxLength: 100
        type: string
    required:
    - app_homepage_url
    - app_name
    - notify_url
    type: object
  merchant.UpdateAPIKeyRequest:
    properties:
      app_description:
        maxLength: 100
        type: string
      app_homepage_url:
        maxLength: 100
        type: string
      app_name:
        maxLength: 20
        type: string
      notify_url:
        maxLength: 100
        type: string
      redirect_uri:
        maxLength: 100
        type: string
    type: object
  model.PayLevel:
    enum:
    - 0
    - 1
    - 2
    - 3
    format: int32
    type: integer
    x-enum-varnames:
    - PayLevelFree
    - PayLevelBasic
    - PayLevelStandard
    - PayLevelPremium
  oauth.CallbackRequest:
    properties:
      code:
        type: string
      state:
        type: string
    type: object
  order.TransactionListRequest:
    properties:
      client_id:
        type: string
      endTime:
        type: string
      page:
        minimum: 1
        type: integer
      page_size:
        maximum: 100
        minimum: 1
        type: integer
      startTime:
        type: string
      status:
        enum:
        - success
        - pending
        - failed
        - expired
        - disputing
        - refund
        - refused
        type: string
      type:
        enum:
        - receive
        - payment
        - transfer
        - community
        type: string
    type: object
  payment.CreateOrderRequest:
    properties:
      amount:
        type: number
      merchant_order_no:
        type: string
      order_name:
        maxLength: 64
        type: string
      payment_type:
        type: string
      remark:
        maxLength: 200
        type: string
    required:
    - amount
    - order_name
    type: object
  payment.PayOrderRequest:
    properties:
      order_no:
        type: string
      pay_key:
        maxLength: 10
        type: string
    required:
    - order_no
    - pay_key
    type: object
  payment.QueryMerchantOrderResponse:
    properties:
      addtime:
        example: "2023-12-08 12:00:00"
        type: string
      code:
        example: 1
        type: integer
      endtime:
        example: "2023-12-08 12:05:00"
        type: string
      money:
        example: "10.00"
        type: string
      msg:
        example: 查询订单号成功！
        type: string
      name:
        example: 商品名称
        type: string
      out_trade_no:
        example: M202312080001
        type: string
      pid:
        example: "1001"
        type: string
      status:
        example: 1
        type: integer
      trade_no:
        example: "123456"
        type: string
      type:
        example: epay
        type: string
    type: object
  payment.RefundMerchantOrderResponse:
    properties:
      code:
        example: 1
        type: integer
      msg:
        example: 退款成功
        type: string
    type: object
  payment.RefundOrderRequest:
    properties:
      key:
        type: string
      money:
        type: number
      out_trade_no:
        type: string
      pid:
        type: string
      trade_no:
        type: integer
    required:
    - key
    - money
    - pid
    - trade_no
    type: object
  payment.TransferRequest:
    properties:
      amount:
        type: number
      pay_key:
        type: string
      recipient_id:
        type: integer
      recipient_username:
        type: string
      remark:
        type: string
    required:
    - amount
    - pay_key
    - recipient_id
    - recipient_username
    type: object
  system_config.CreateSystemConfigRequest:
    properties:
      description:
        maxLength: 255
        type: string
      key:
        maxLength: 64
        type: string
      value:
        maxLength: 255
        type: string
    required:
    - key
    - value
    type: object
  system_config.UpdateSystemConfigRequest:
    properties:
      description:
        maxLength: 255
        type: string
      value:
        maxLength: 255
        type: string
    required:
    - value
    type: object
  user.UpdatePayKeyRequest:
    properties:
      pay_key:
        maxLength: 10
        type: string
    required:
    - pay_key
    type: object
  user_pay_config.CreateUserPayConfigRequest:
    properties:
      daily_limit:
        type: integer
      fee_rate:
        type: number
      level:
        $ref: '#/definitions/model.PayLevel'
      max_score:
        type: integer
      min_score:
        minimum: 0
        type: integer
      score_rate:
        type: number
    required:
    - fee_rate
    - score_rate
    type: object
  user_pay_config.UpdateUserPayConfigRequest:
    properties:
      daily_limit:
        type: integer
      fee_rate:
        type: number
      max_score:
        type: integer
      min_score:
        minimum: 0
        type: integer
      score_rate:
        type: number
    required:
    - fee_rate
    - score_rate
    type: object
  util.ResponseAny:
    properties:
      data: {}
      error_msg:
        example: ""
        type: string
    type: object
info:
  contact: {}
  title: LINUX DO PAY
  version: 0.1.0
paths:
  /api.php:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: act
        type: string
      - in: query
        name: key
        required: true
        type: string
      - in: query
        name: out_trade_no
        type: string
      - in: query
        name: pid
        required: true
        type: string
      - in: query
        name: trade_no
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payment.QueryMerchantOrderResponse'
      tags:
      - payment
    post:
      consumes:
      - application/json
      parameters:
      - description: 退款请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/payment.RefundOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payment.RefundMerchantOrderResponse'
      tags:
      - payment
  /api/v1/admin/system-configs:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/system_config.CreateSystemConfigRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
  /api/v1/admin/system-configs/{key}:
    delete:
      parameters:
      - description: 配置键
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
    get:
      parameters:
      - description: 配置键
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
    put:
      consumes:
      - application/json
      parameters:
      - description: 配置键
        in: path
        name: key
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/system_config.UpdateSystemConfigRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
  /api/v1/admin/user-pay-configs:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user_pay_config.CreateUserPayConfigRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
  /api/v1/admin/user-pay-configs/{id}:
    delete:
      parameters:
      - description: 配置ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
    get:
      parameters:
      - description: 配置ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
    put:
      consumes:
      - application/json
      parameters:
      - description: 配置ID
        in: path
        name: id
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user_pay_config.UpdateUserPayConfigRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
  /api/v1/config/public:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - config
  /api/v1/health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - health
  /api/v1/merchant/api-keys:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - merchant
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/merchant.CreateAPIKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - merchant
  /api/v1/merchant/api-keys/{id}:
    delete:
      parameters:
      - description: API Key ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - merchant
    get:
      parameters:
      - description: API Key ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - merchant
    put:
      consumes:
      - application/json
      parameters:
      - description: API Key ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/merchant.UpdateAPIKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - merchant
  /api/v1/merchant/payment:
    post:
      consumes:
      - application/json
      parameters:
      - description: 支付订单请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/payment.PayOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - payment
  /api/v1/merchant/payment/order:
    get:
      consumes:
      - application/json
      parameters:
      - description: 订单号
        in: query
        name: order_no
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - payment
  /api/v1/oauth/callback:
    post:
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/oauth.CallbackRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - oauth
  /api/v1/oauth/login:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - oauth
  /api/v1/oauth/logout:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - oauth
  /api/v1/oauth/user-info:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - oauth
  /api/v1/order/dispute:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dispute.CreateDisputeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - order
  /api/v1/order/dispute/close:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dispute.CloseDisputeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - order
  /api/v1/order/disputes:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        schema:
          $ref: '#/definitions/dispute.ListDisputesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - order
  /api/v1/order/disputes/merchant:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        schema:
          $ref: '#/definitions/dispute.ListDisputesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - order
  /api/v1/order/refund-review:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dispute.RefundReviewRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - order
  /api/v1/order/transactions:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        schema:
          $ref: '#/definitions/order.TransactionListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - order
  /api/v1/payment/transfer:
    post:
      consumes:
      - application/json
      parameters:
      - description: 转账请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/payment.TransferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - payment
  /api/v1/user/pay-key:
    put:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.UpdatePayKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - user
  /pay/submit.php:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/payment.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - payment
swagger: "2.0"
